x-healthcheck: &default-healthcheck
  interval: 5s
  retries: 5

x-service-defaults: &service-defaults
  build:
    args:
      BUILD_ENV: production

services:
  ollama:
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 21240:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - 21220:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=es-chipper-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=http://localhost:8080"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - backend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
    deploy:
      resources:
        limits:
          memory: 16g

  elasticvue:
    image: cars10/elasticvue
    ports:
      - "20030:8080"
    environment:
      ELASTICVUE_CLUSTERS: '[{"name":"es-chipper-cluster","uri":"http://elasticsearch:9200"}]'
    restart: always
    networks:
      - backend

  api:
    <<: *service-defaults
    build:
      context: ../services/api
    ports:
      - 21210:8000
    env_file: ../services/api/.env
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend
      - frontend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]

  web:
    <<: *service-defaults
    build:
      context: ../services/web
    ports:
      - 21200:5000
    env_file: ../services/web/.env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - frontend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]

networks:
  frontend:
  backend:

volumes:
  ollama-data:
  elasticsearch-data:
